### ISSUE TITLE
more suggestions for DAQ page 

### ISSUE THREAD

**Issue by NataschaRupp** [coderdj/emo#8] opened 2016-07-23 13:58 UTC
Hi Dan, as I'm using the DAQ page quite intensively, I have some more suggestions how it could be improved. Maybe you also think that the the following points could be useful:
- sometimes the text, that I'm about to write in the comment field of a run, disappears before I can click on the button "comment". Like this it is not possible to add it and I have to write it somewhere else, copy it and be fast in pasting it ;)
- it would be nice to have an additional "changing to previous, 1,2, ... last" page button on the top of the run list page
- sometimes it would also be good to hide the "more detail" section for each run on the run list side to get more space for the main column of the runs (especially the top comment column would than be visible all the time which makes fast comparison easier). Probably this is also an issue of having only a 13" screen :)
- on the tablet I cannot start more than 10 runs each time, on my laptop it is working

Cheers and thanks, Natascha

**Comment by IoanaCodrina** [comment] 2016-07-27 15:09
Hi Dan, 

For the alarm comments and closure would be easier to have two buttons: "New comment" and the second one: "Comment and close" instead of the check button.

Cheers and thanks,
Ioana

**Comment by coderdj** [comment] 2016-08-17 15:37
Thanks for the comments. Almost everything is now fixed as you suggest. 
- Runs detail doesn't auto update anymore (that way why it was deleting comments sometimes)
- There's a pagination bar on the top of the runs table as well
- The "more detail" section on the runs page only appears if you click a green button. You can hide it again with a button.
- I could not reproduce Natasha's last issue. I assume it is with the shifter tablet? If this is the case we can test it easily if someone else complains. 
- Fixed Ioana's request, but unfortunately had to add an extra dialog asking shifters if they "really" want to close an issue.

**Closed as completed by coderdj** 2016-08-17 15:37 UTC

**Comment by NataschaRupp** [comment] 2016-08-17 21:53
Hi Dan, 
thanks a lot, I really like it. Yes, I think the issue of only being able to start a maximum run number of ten was on the tablet. But in this case you can repeat the starting procedure and get more runs or simply do it from the laptop.
